---
- name: Filebeat download and installation
  hosts: webservers
  become: true
  tasks:

  - name: Download filebeat .deb files
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

  - name: Install filebeat .deb files
    command: dpkg -i filebeat-7.4.0-amd64.deb

  - name: Get filebeat config files
    copy:
      src: /etc/ansible/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: Enable module system
    command: filebeat modules enable system

  - name: Filebeat setup
    command: filebeat setup

  - name: Enable start
    command: service filebeat start

  - name: Enable filebeat on startup
    systemd:
      name: filebeat
      enabled: yes
